Start of the complete rewrite

diff --git a/ais b/ais
--- a/ais
+++ b/ais
@@ -1,82 +1,115 @@
 #!/bin/bash
 
 if [[ -f `pwd`/sharedfuncs ]]; then
-  source sharedfuncs
+  . sharedfuncs
 else
   echo "Missing file: sharedfuncs"
   exit 1
 fi
 
-# VARIABLES
-  CONNECTION="wireless"         #(wired/wireless)
-  LOCALE="en_US"
-  KEYMAP="dvorak"               #(us)
-  TIMEZONE="Europe/Amsterdam"
-  HARDWARECLOCK="utc"           #(utc/localtime)
-  HOSTNAME="arch-laptop"
-  INSTALLPARTITION="sda"        #(sda/sdb/sdc)
+if [ -d _ais ]; then
+    for files in _ais/*; do
+        . $files
+    done
+else
+  echo "Missing directory: _ais"
+  exit 1
+fi
 
-# COMMON FUNCTIONS
-  arch_chroot() {
-    arch-chroot $MOUNTPOINT /bin/bash -c "${1}"
-  }
 
-check_connection $CONNECTION
-
+print_title "https://wiki.archlinux.org/index.php/Arch_Install_Scripts"
+print_info "The Arch Install Scripts are a set of Bash scripts that simplify Arch installation."
+pause_function
+check_boot_system
+check_connection
+check_trim
 # Update mirrorlist
 pacman -Sy
 
-# Install the base system
-pacstrap ${MOUNTPOINT} base base-devel linux-headers
-
-case "$CONNECTION" in
-  wired)
-    arch_chroot "systemctl enable dhcpcd@${WIRED_DEV}.service"
-    ;;
-  wireless)
-    pacstrap ${MOUNTPOINT} iw wireless_tools wpa_actiond wpa_supplicant dialog
-    ;;
-esac
-
-# Generate an fstab
-genfstab -U -p ${MOUNTPOINT} >> ${MOUNTPOINT}/etc/fstab
-nano ${MOUNTPOINT}/etc/fstab
-
-# Locale
-arch_chroot "sed -i '/'${LOCALE}.UTF-8'/s/^#//' /etc/locale.gen"
-arch_chroot "locale-gen"
-echo LANG=${LOCALE}.UTF-8 > ${MOUNTPOINT}/etc/locale.conf
-export LANG=${LOCALE}.UTF-8
-
-# Console keymap
-echo "KEYMAP=${KEYMAP}" > ${MOUNTPOINT}/etc/vconsole.conf
-
-# Time zone
-arch_chroot "ln -s /usr/share/zoneinfo/${TIMEZONE} /etc/localtime"
-
-# Hardware clock
-arch_chroot "hwclock --systohc --${HARDWARECLOCK}"
-
-# Hostname
-echo ${HOSTNAME} > ${MOUNTPOINT}/etc/hostname
-arch_chroot "sed -i '/127.0.0.1/s/$/ '${HOSTNAME}'/' /etc/hosts"
-arch_chroot "sed -i '/::1/s/$/ '${HOSTNAME}'/' /etc/hosts"
-
-# Create an initial ramdisk environment
-arch_chroot "mkinitcpio -p linux"
-
-# Install and configure a bootloader
-pacstrap ${MOUNTPOINT} grub os-prober
-arch_chroot "grub-install --target=i386-pc --recheck /dev/${INSTALLPARTITION}"
-arch_chroot "grub-mkconfig -o /boot/grub/grub.cfg"
-
-# Set the root password
-echo "${BLUE}Enter your new root password${RESET}"
-arch_chroot "passwd"
-
-echo "${RED}A copy of RiyyiAIC will be placed in /root directory of your new system ${RESET}"
-cp -R `pwd` ${MOUNTPOINT}/root
-
-read -p "${BLUE}Reboot system? [y/N]${RESET} " x
-[[ $x == "y" ]] || [[ $x == "Y" ]] || [[ -z $x ]] && reboot
-exit 0
+while true
+do
+  print_title "ARCHLINUX INSTALL && CONFIGURE - https://github.com/riyyi/aic"
+  echo " 1) $(mainmenu_item "${checklist[1]}" "Select Keymap")"
+  echo " 2) $(mainmenu_item "${checklist[2]}" "Select Editor")"
+  echo " 3) $(mainmenu_item "${checklist[3]}" "Configure Mirrorlist")"
+  echo " 4) $(mainmenu_item "${checklist[4]}" "Partition Scheme")"
+  echo " 5) $(mainmenu_item "${checklist[5]}" "Install Base System")"
+  echo " 6) $(mainmenu_item "${checklist[6]}" "Configure Fstab")"
+  echo " 7) $(mainmenu_item "${checklist[7]}" "Configure Locale")"
+  echo " 8) $(mainmenu_item "${checklist[8]}" "Configure Timezone")"
+  echo " 9) $(mainmenu_item "${checklist[9]}" "Configure Hardware Clock")"
+  echo "10) $(mainmenu_item "${checklist[10]}" "Configure Hostname")"
+  echo "11) $(mainmenu_item "${checklist[11]}" "Configure Mkinitcpio")"
+  echo "12) $(mainmenu_item "${checklist[12]}" "Install Bootloader")"
+  echo "13) $(mainmenu_item "${checklist[13]}" "Root Password")"
+  echo ""
+  echo " d) Done"
+  echo ""
+  read_input_options
+  for OPT in ${OPTIONS[@]}; do
+    case "$OPT" in
+      1)
+        select_keymap
+        checklist[1]=1
+        ;;
+      2)
+        select_editor #! automatic mode
+        checklist[2]=1
+        ;;
+      3)
+        configure_mirrorlist
+        checklist[3]=1
+        ;;
+      4)
+        umount_partitions
+        create_partition_scheme
+        format_partitions
+        checklist[4]=1
+        ;;
+      5)
+        install_base_system
+        configure_keymap
+        checklist[5]=1
+        ;;
+      6)
+        configure_fstab
+        checklist[6]=1
+        ;;
+      7)
+        configure_locale
+        checklist[7]=1
+        ;;
+      8)
+        configure_timezone
+        checklist[8]=1
+        ;;
+      9)
+        configure_hardwareclock
+        checklist[9]=1
+        ;;
+      10)
+        configure_hostname
+        checklist[10]=1
+        ;;
+      11)
+        configure_mkinitcpio
+        checklist[11]=1
+        ;;
+      12)
+        install_bootloader
+        configure_bootloader
+        checklist[12]=1
+        ;;
+      13)
+        root_password
+        checklist[13]=1
+        ;;
+      "d")
+        finish
+        ;;
+      *)
+        invalid_option
+        ;;
+    esac
+  done
+done
diff --git a/sharedfuncs b/sharedfuncs
--- a/sharedfuncs
+++ b/sharedfuncs
@@ -1,236 +1,10 @@
 #!/bin/bash
 
-# VARIABLES
-  # COLORS
-    BOLD=$(tput bold)
-    UNDERLINE=$(tput sgr 0 1)
-    RESET=$(tput sgr0)
-    # regular colors
-    RED=$(tput setaf 1)
-    GREEN=$(tput setaf 2)
-    YELLOW=$(tput setaf 3)
-    BLUE=$(tput setaf 4)
-    PURPLE=$(tput setaf 5)
-    CYAN=$(tput setaf 6)
-    WHITE=$(tput setaf 7)
-    # bold
-    BRED=${Bold}$(tput setaf 1)
-    BGREEN=${Bold}$(tput setaf 2)
-    BYELLOW=${Bold}$(tput setaf 3)
-    BBLUE=${Bold}$(tput setaf 4)
-    BPURPLE=${Bold}$(tput setaf 5)
-    BCYAN=${Bold}$(tput setaf 6)
-    BWHITE=${Bold}$(tput setaf 7)
-  
-  ARCHI=`uname -m`
-  MOUNTPOINT="/mnt"
-
-  # LOG FILE
-    LOG="install_error.log"
-    [[ -f $LOG ]] && rm -f $LOG
-    PKG_FAIL="install_pkg_fail_list.log"
-    [[ -f $PKG_FAIL ]] && rm -f $PKG_FAIL
-    
-# COMMON FUNCTIONS
-  progress() {
-    while true; do
-      kill -0 $PID &> /dev/null;
-      if [[ $? == 0 ]]; then
-        sleep 0.25
-      else
-        wait $PID
-	    RETCODE=$?
-	    echo "$PID's retcode: $RETCODE" >> $LOG
-	    if [[ $RETCODE == 0 ]] || [[ $RETCODE == 255 ]]; then
-	      echo -e "${GREEN}(success)${RESET}"
-	    else
-	      echo -e "${RED}(failed)${RESET}"
-	      echo -e "$PKG" >> $PKG_FAIL
-	    fi
-	    break
-      fi
+if [ -d _sharedfuncs ]; then
+    for f in _sharedfuncs/*; do
+        . $f
     done
-  }
-
-  check_root() {
-    if [[ "$(id -u)" != "0" ]]; then
-      echo "${RED}ERROR! You must execute the script as the 'root' user.${RESET}"
-      exit
-    fi
-  }
-
-  check_archlinux() {
-    if [[ ! -e /etc/arch-release ]]; then
-      echo "ERROR! You must execute the script on Arch Linux."
-    fi
-  }
-
-  check_hostname() {
-    if [[ `echo ${HOSTNAME} | sed 's/ //g'` == "" ]]; then
-      echo "ERROR! Hostname is not configured."
-    fi
-  }
-
-  check_pacman_blocked() {
-    if [[ -f /var/lib/pacman/db.lck ]]; then
-      echo "${RED}ERROR! Pacman is blocked. \nIf not running remove /var/lib/pacman/db.lck.${RESET}"
-    fi
-  }
-
-  check_connection(){
-    connection_test() {
-      ping -c 1 google.com &> /dev/null && return 1 || return 0
-    }
-    WIRED_DEV=`ip link | grep enp | awk '{print $2}' | sed 's/://' | sed '1!d'`
-    WIRELESS_DEV=`ip link | grep wlp | awk '{print $2}' | sed 's/://' | sed '1!d'`
-    if connection_test; then
-      echo "${RED}ERROR! Connection not found.${RESET}"
-
-#case "$1" in
-#wired)
-#systemctl start dhcpcd@${WIRED_DEV}.service
-#;;
-#wireless)
-#ip link set ${WIRELESS_DEV} up
-#wifi-menu ${WIRELESS_DEV}
-#;;
-#esac
-#check_connection
-    fi
-  }
-
-  start_module() {
-    modprobe $1
-  }
-
-  add_module() { #{{{
-    #check if the number of arguments is less then 2
-    for MODULE in $1; do
-      [[ $# -lt 2 ]] && MODULE_NAME="$MODULE" || MODULE_NAME="$2"
-      echo "$MODULE" >> /etc/modules-load.d/$MODULE_NAME.conf
-      start_module "$MODULE"
-    done
-  }
-
-  add_repository() {
-    REPO=${1}
-    URL=${2}
-    [[ -n ${3} ]] && SIGLEVEL="\nSigLevel = ${3}" || SIGLEVEL=""
-    CHECK_REPO=`grep -F "${REPO}" /etc/pacman.conf`
-    if [[ -z $CHECK_REPO ]]; then
-      echo -e "\n[${REPO}]${SIGLEVEL}\nServer = ${URL}" >> /etc/pacman.conf
-      system_update
-    fi
-  }
-
-  # This option will avoid any problem with packages install
-  check_multilib(){
-    if [[ $ARCHI == x86_64 ]]; then
-      local MULTILIB=`grep -n "\[multilib\]" /etc/pacman.conf | cut -f1 -d:`
-      if [[ -z $MULTILIB ]]; then
-        echo -e "\n[multilib]\nInclude = /etc/pacman.d/mirrorlist" >> /etc/pacman.conf
-        echo -e '\nMultilib repository added into pacman.conf file'
-      else
-        sed -i "${MULTILIB}s/^#//" /etc/pacman.conf
-        local MULTILIB=$(( $MULTILIB + 1 ))
-        sed -i "${MULTILIB}s/^#//" /etc/pacman.conf
-      fi
-    fi
-  }
-
-  add_key() {
-    pacman-key -r $1
-    pacman-key --lsign-key $1
-  }
-
-  pacman_key(){
-    if [[ ! -d /etc/pacman.d/gnupg ]]; then
-      package_install "haveged"
-      haveged -w 1024
-      pacman-key --init
-      pacman-key --populate archlinux
-      pkill haveged
-      package_remove "haveged"
-    fi
-  }
-
-  add_line() {
-    ADD_LINE=${1}
-    FILEPATH=${2}
-    CHECK_LINE=`grep -F "${ADD_LINE}" ${FILEPATH}`
-    [[ -z $CHECK_LINE ]] && echo "${ADD_LINE}" >> ${FILEPATH}
-  }
-
-  # Check if a package is already installed
-  is_package_installed() {
-    for PKG in $1; do
-      pacman -Q $PKG &> /dev/null && return 0;
-    done
-    return 1
-  }
-
-  aui_download_packages() {
-    for PKG in $1; do
-      # Exec command as user instead of root
-      su - ${username} -c "
-        [[ ! -d aui_packages ]] && mkdir aui_packages
-        cd aui_packages
-        curl -o $PKG.tar.gz https://aur.archlinux.org/packages/${PKG:0:2}/$PKG/$PKG.tar.gz
-        tar zxvf $PKG.tar.gz
-        rm $PKG.tar.gz
-        cd $PKG
-        makepkg -csi --noconfirm
-      "
-    done
-  }
-
-  # Install package from aur
-  aur_package_install() {
-    for PKG in $1; do
-      if ! is_package_installed "${PKG}" ; then
-        echo -ne "${PKG} (AUR) "
-        ${AUR_PKG_MANAGER} --noconfirm -S ${PKG} >>"$LOG" 2>&1 &
-        PID=$!;progress $PID
-      else
-        echo -e "${YELLOW}Warning: ${PKG} is up to date --skipping${RESET}"
-      fi
-    done
-  }
-
-  # Install package using pacman
-  package_install() {
-    for PKG in ${1}; do
-      if ! is_package_installed "${PKG}" ; then
-        echo -ne "${PKG} "
-        pacman -S --noconfirm --needed ${PKG} >>"$LOG" 2>&1 &
-        PID=$!;progress $PID
-      else
-        echo -e "${YELLOW}Warning: ${PKG} is up to date --skipping${RESET}"
-      fi
-    done
-  }
-
-  # Remove package
-  package_remove() {
-    for PKG in ${1}; do
-      if is_package_installed "${PKG}" ; then
-        echo -ne "${PKG} "
-        pacman -Rcsn --noconfirm ${PKG} >>"$LOG" 2>&1 &
-        PID=$!;progress $PID
-      else
-        echo -e "${YELLOW}Error: target not found: ${PKG}${RESET}"
-      fi
-    done
-  }
-
-  system_update() {
-    pacman -Syy
-  }
-
-  system_ctl() {
-    local ACTION=${1}
-    local OBJECT=${2}
-    echo -ne "systemctl ${ACTION} ${OBJECT} "
-    systemctl ${ACTION} ${OBJECT} >> "$LOG" 2>&1
-    PID=$!;progress $PID
-  }
+else
+  echo "Missing directory: _sharedfuncs"
+  exit 1
+fi
